### ISSUE TITLE
Deprecate This Repo

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/openshift-config-loader#56]
The openshift rest client is no longer using this library.  it is using the kubernetes client here:  https://github.com/godaddy/kubernetes-client

We an now deprecate this repo. 

Needs a Readme update, and a publish to npm with the deprecation flag(https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions)

**Comment by helio-frota** [comment]
landed https://github.com/nodeshift/openshift-config-loader/commit/3283f358cbb329249fd092f2525625cf3062074a
